Repository Frey0xD/AllInHacktoberfest, pull requests merged in 2022-10, with the labels that each got.

#2 added a validation for user input
  rockpaperscissor.py
Labels: good first issue, hactoberfest-accepted

#5 removed else statement for issue#3
  rockpaperscissor.py
Labels: hactoberfest-accepted

#8 ping pong game
  ping pong game1.py
Labels: good first issue, hactoberfest-accepted

#11 snake game using python
  snake game
Labels: good first issue, hactoberfest-accepted

#10 Add tic-tac-toe game
  tictactoe.py
Labels: good first issue, hactoberfest-accepted

#17 Flappy Game
  flappy.py
Labels: good first issue, hactoberfest-accepted

#16 Added Bubble Shooter
  BubbleShooter.py
  README.md
  img/bubble.png
Labels: documentation, good first issue, hactoberfest-accepted

#20 Tic Tac Toe in C.c
  Tic Tac Toe in C.c.c
Labels: good first issue, hactoberfest-accepted

#23 updated the comments in balloon pop game
  ballon_pop.py
Labels: good first issue, hactoberfest-accepted
