Repository Frey0xD/AllInHacktoberfest, pull requests merged in 2023-10, with the labels that each got.

#36 Added balloon shooting game
  Balloon Shooting game/audio/.md
  Balloon Shooting game/audio/balloonPop.wav
  Balloon Shooting game/audio/bowRelease.mp3
  Balloon Shooting game/audio/gameOver.mp3
  Balloon Shooting game/audio/gameStart.wav
  Balloon Shooting game/game.html
  Balloon Shooting game/images/.md
  Balloon Shooting game/images/balloons.png
  Balloon Shooting game/images/bg.jpg
  Balloon Shooting game/images/red-balloon-clipart-6.png
  Balloon Shooting game/main.css
  Balloon Shooting game/main.js
  Balloon Shooting game/readme.md
Labels: hactoberfest-accepted

#32 Snake-game-init
  Snake_Game_cpp/README.md
  Snake_Game_cpp/Snake_game_using_cpp.cpp
  Snake_Game_cpp/a.exe
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#35 Bomb_defuse_game_added
  Bomb_Defuser/app.js
  Bomb_Defuser/readMe
  Bomb_Defuser/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#50 Update README.md
  README.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#58 dwm
  Linux/DWM/LICENSE
  Linux/DWM/Makefile
  Linux/DWM/README.md
  Linux/DWM/config.def.h
  Linux/DWM/config.mk
  Linux/DWM/drw.c
  Linux/DWM/drw.h
  Linux/DWM/dwm.1
  Linux/DWM/dwm.c
  Linux/DWM/dwm.png
  Linux/DWM/transient.c
  Linux/DWM/util.c
  Linux/DWM/util.h
Labels: hacktoberfest-accepted, hacktoberfest

#67 Added DSA folder and different Searching and Sorting algorithms in it
  DSA/Searching/BinarySearch.py
  DSA/Searching/LinearSearch.py
  DSA/Sorting/MergeSort.py
  DSA/Sorting/QuickSort.py
Labels: hacktoberfest-accepted, hacktoberfest, DSA

#64 Added clothing website
  WebDev/Fauxica/images/clothing1.jpg
  WebDev/Fauxica/images/clothing2.jpg
  WebDev/Fauxica/images/clothing3.jpg
  WebDev/Fauxica/images/confetti.svg
  WebDev/Fauxica/images/fauxica.svg
  WebDev/Fauxica/images/logo.svg
  WebDev/Fauxica/images/tag.svg
  WebDev/Fauxica/index.html
  WebDev/Fauxica/style.css
Labels: hacktoberfest-accepted, hacktoberfest, Web Development

#60 DSA Changes and one ping pong game will include
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  .vscode/settings.json
  DSA/C/linklist.cpp
  DSA/python/__init__.py
  DSA/python/linklist.py
  GameDev/Ping-pong-game-autopilot-using-ML/LICENSE
  GameDev/Ping-pong-game-autopilot-using-ML/README.md
  GameDev/Ping-pong-game-autopilot-using-ML/data.csv
  GameDev/Ping-pong-game-autopilot-using-ML/model.Ipynb
  GameDev/Ping-pong-game-autopilot-using-ML/model_v1.joblib
  GameDev/Ping-pong-game-autopilot-using-ML/opencv_ping_pong_game.py
  GameDev/tic tac toe java GUI.java
Labels: hacktoberfest-accepted, hacktoberfest, Reviewing

#70 Added Insertion Sort
  DSA/Sorting/InsertionSort.py
Labels: hacktoberfest-accepted, hacktoberfest

#66 Dice roller
  .DS_Store
  GameDev/.DS_Store
  GameDev/DiceRoller/.gitignore
  GameDev/DiceRoller/.idea/.gitignore
  GameDev/DiceRoller/.idea/.name
  GameDev/DiceRoller/.idea/compiler.xml
  GameDev/DiceRoller/.idea/gradle.xml
  GameDev/DiceRoller/.idea/kotlinc.xml
  GameDev/DiceRoller/.idea/misc.xml
  GameDev/DiceRoller/.idea/vcs.xml
  GameDev/DiceRoller/app/.gitignore
  GameDev/DiceRoller/app/build.gradle
  GameDev/DiceRoller/app/proguard-rules.pro
  GameDev/DiceRoller/app/src/androidTest/java/com/example/diceroller/ExampleInstrumentedTest.kt
  GameDev/DiceRoller/app/src/main/AndroidManifest.xml
  GameDev/DiceRoller/app/src/main/ic_launcher-playstore.png
  GameDev/DiceRoller/app/src/main/java/com/example/diceroller/MainActivity.kt
  GameDev/DiceRoller/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  GameDev/DiceRoller/app/src/main/res/drawable/dice_1.xml
  GameDev/DiceRoller/app/src/main/res/drawable/dice_2.xml
  GameDev/DiceRoller/app/src/main/res/drawable/dice_3.xml
  GameDev/DiceRoller/app/src/main/res/drawable/dice_4.xml
  GameDev/DiceRoller/app/src/main/res/drawable/dice_5.xml
  GameDev/DiceRoller/app/src/main/res/drawable/dice_6.xml
  GameDev/DiceRoller/app/src/main/res/drawable/empty_dice.xml
  GameDev/DiceRoller/app/src/main/res/drawable/ic_launcher_background.xml
  GameDev/DiceRoller/app/src/main/res/layout/activity_main.xml
  GameDev/DiceRoller/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  GameDev/DiceRoller/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  GameDev/DiceRoller/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  GameDev/DiceRoller/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  GameDev/DiceRoller/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  GameDev/DiceRoller/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  GameDev/DiceRoller/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  GameDev/DiceRoller/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  GameDev/DiceRoller/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  GameDev/DiceRoller/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  GameDev/DiceRoller/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  GameDev/DiceRoller/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  GameDev/DiceRoller/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  GameDev/DiceRoller/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  GameDev/DiceRoller/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  GameDev/DiceRoller/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  GameDev/DiceRoller/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  GameDev/DiceRoller/app/src/main/res/values-night/themes.xml
  GameDev/DiceRoller/app/src/main/res/values/colors.xml
  GameDev/DiceRoller/app/src/main/res/values/strings.xml
  GameDev/DiceRoller/app/src/main/res/values/themes.xml
  GameDev/DiceRoller/app/src/main/res/xml/backup_rules.xml
  GameDev/DiceRoller/app/src/main/res/xml/data_extraction_rules.xml
  GameDev/DiceRoller/app/src/test/java/com/example/diceroller/ExampleUnitTest.kt
  GameDev/DiceRoller/build.gradle
  GameDev/DiceRoller/gradle.properties
  GameDev/DiceRoller/gradle/wrapper/gradle-wrapper.jar
  GameDev/DiceRoller/gradle/wrapper/gradle-wrapper.properties
  GameDev/DiceRoller/gradlew
  GameDev/DiceRoller/gradlew.bat
  GameDev/DiceRoller/settings.gradle
Labels: hacktoberfest-accepted, hacktoberfest

#63 message encryption script
  CyberSecurity/Message_encryption/encryption.py
Labels: hacktoberfest-accepted, hacktoberfest

#42 Add a simple port scanning tool
  Cybersecuritytool/README.md
  Cybersecuritytool/cyber.py
Labels: hacktoberfest-accepted, hacktoberfest, Reviewing

#78 Github Page
  img/bg.png
  index.html
  style.css
Labels: hacktoberfest-accepted, hacktoberfest, Web Development

#40 Sudoko solver code
  3-D_Tshirt_Designer/client/.gitignore
  3-D_Tshirt_Designer/client/index.html
  3-D_Tshirt_Designer/client/package-lock.json
  3-D_Tshirt_Designer/client/package.json
  3-D_Tshirt_Designer/client/postcss.config.js
  3-D_Tshirt_Designer/client/public/react.png
  3-D_Tshirt_Designer/client/public/shirt_baked.glb
  3-D_Tshirt_Designer/client/public/threejs.png
  3-D_Tshirt_Designer/client/public/vite.svg
  3-D_Tshirt_Designer/client/src/App.jsx
  3-D_Tshirt_Designer/client/src/assets/ai.png
  3-D_Tshirt_Designer/client/src/assets/download.png
  3-D_Tshirt_Designer/client/src/assets/file.png
  3-D_Tshirt_Designer/client/src/assets/index.js
  3-D_Tshirt_Designer/client/src/assets/logo-tshirt.png
  3-D_Tshirt_Designer/client/src/assets/stylish-tshirt.png
  3-D_Tshirt_Designer/client/src/assets/swatch.png
  3-D_Tshirt_Designer/client/src/canvas/Backdrop.jsx
  3-D_Tshirt_Designer/client/src/canvas/CameraRig.jsx
  3-D_Tshirt_Designer/client/src/canvas/Shirt.jsx
  3-D_Tshirt_Designer/client/src/canvas/index.jsx
  3-D_Tshirt_Designer/client/src/components/AIPicker.jsx
  3-D_Tshirt_Designer/client/src/components/ColorPicker.jsx
  3-D_Tshirt_Designer/client/src/components/CustomButton.jsx
  3-D_Tshirt_Designer/client/src/components/FilePicker.jsx
  3-D_Tshirt_Designer/client/src/components/Tab.jsx
  3-D_Tshirt_Designer/client/src/components/index.js
  3-D_Tshirt_Designer/client/src/config/config.js
  3-D_Tshirt_Designer/client/src/config/constants.js
  3-D_Tshirt_Designer/client/src/config/helpers.js
  3-D_Tshirt_Designer/client/src/config/motion.js
  3-D_Tshirt_Designer/client/src/index.css
  3-D_Tshirt_Designer/client/src/main.jsx
  3-D_Tshirt_Designer/client/src/pages/Customizer.jsx
  3-D_Tshirt_Designer/client/src/pages/Home.jsx
  3-D_Tshirt_Designer/client/src/store/index.js
  3-D_Tshirt_Designer/client/tailwind.config.js
  3-D_Tshirt_Designer/client/vite.config.js
  3-D_Tshirt_Designer/server/index.js
  3-D_Tshirt_Designer/server/package.json
  3-D_Tshirt_Designer/server/routes/dalle.routes.js
  Sudoko.cpp
  Sudoko_build/sudoko/app.css
  Sudoko_build/sudoko/index.html
  Sudoko_build/sudoko/static/images/icon.png
  Sudoko_build/sudoko/static/js/app.js
  Sudoko_build/sudoko/static/js/constant.js
  Sudoko_build/sudoko/static/js/sudoku.js
Labels: hacktoberfest-accepted, hacktoberfest, Web Development

#83 Linux Command MindMap
  Linux/Linux_Command_MindMap.png
Labels: hacktoberfest-accepted, hacktoberfest, Linux

#85 web dev snake game
  web dev snake/Minecraft Eating.mp3
  web dev snake/README.md
  web dev snake/image.png
  web dev snake/index.html
  web dev snake/mixkit-alien-technology-hum-2134.wav
  web dev snake/mixkit-arcade-space-shooter-dead-notification-272.wav
  web dev snake/mixkit-bonus-earned-in-video-game-2058.wav
  web dev snake/mixkit-game-blood-pop-slide-2363.wav
  web dev snake/task1.css
  web dev snake/task1.js
Labels: hacktoberfest-accepted, hacktoberfest, Web Development, Game Development

#86 Google sheeeet clone
  google-sheet-clone/README.md
  google-sheet-clone/Screenshot 2023-10-08 185842.png
  google-sheet-clone/charcodeat.js
  google-sheet-clone/index.html
  google-sheet-clone/index.js
  google-sheet-clone/styles.css
Labels: hacktoberfest-accepted, hacktoberfest

#87 Fake_news detection restful api project and some DSA new algorithum
  CyberSecurity/Fake_news/Fake_news/__init__.py
  CyberSecurity/Fake_news/Fake_news/__pycache__/__init__.cpython-310.pyc
  CyberSecurity/Fake_news/Fake_news/__pycache__/settings.cpython-310.pyc
  CyberSecurity/Fake_news/Fake_news/__pycache__/urls.cpython-310.pyc
  CyberSecurity/Fake_news/Fake_news/__pycache__/wsgi.cpython-310.pyc
  CyberSecurity/Fake_news/Fake_news/asgi.py
  CyberSecurity/Fake_news/Fake_news/settings.py
  CyberSecurity/Fake_news/Fake_news/urls.py
  CyberSecurity/Fake_news/Fake_news/wsgi.py
  CyberSecurity/Fake_news/app/__init__.py
  CyberSecurity/Fake_news/app/__pycache__/__init__.cpython-310.pyc
  CyberSecurity/Fake_news/app/__pycache__/admin.cpython-310.pyc
  CyberSecurity/Fake_news/app/__pycache__/apps.cpython-310.pyc
  CyberSecurity/Fake_news/app/__pycache__/models.cpython-310.pyc
  CyberSecurity/Fake_news/app/__pycache__/serializer.cpython-310.pyc
  CyberSecurity/Fake_news/app/__pycache__/urls.cpython-310.pyc
  CyberSecurity/Fake_news/app/__pycache__/views.cpython-310.pyc
  CyberSecurity/Fake_news/app/admin.py
  CyberSecurity/Fake_news/app/apps.py
  CyberSecurity/Fake_news/app/migrations/0001_initial.py
  CyberSecurity/Fake_news/app/migrations/0002_rename_title_fakenews_model_newstitle.py
  CyberSecurity/Fake_news/app/migrations/0003_rename_newstitle_fakenews_model_title.py
  CyberSecurity/Fake_news/app/migrations/0004_alter_fakenews_model_date.py
  CyberSecurity/Fake_news/app/migrations/0005_alter_fakenews_model_date.py
  CyberSecurity/Fake_news/app/migrations/__init__.py
  CyberSecurity/Fake_news/app/migrations/__pycache__/0001_initial.cpython-310.pyc
  CyberSecurity/Fake_news/app/migrations/__pycache__/0002_rename_title_fakenews_model_newstitle.cpython-310.pyc
  CyberSecurity/Fake_news/app/migrations/__pycache__/0003_rename_newstitle_fakenews_model_title.cpython-310.pyc
  CyberSecurity/Fake_news/app/migrations/__pycache__/0004_alter_fakenews_model_date.cpython-310.pyc
  CyberSecurity/Fake_news/app/migrations/__pycache__/0005_alter_fakenews_model_date.cpython-310.pyc
  CyberSecurity/Fake_news/app/migrations/__pycache__/__init__.cpython-310.pyc
  CyberSecurity/Fake_news/app/models.py
  CyberSecurity/Fake_news/app/serializer.py
  CyberSecurity/Fake_news/app/tests.py
  CyberSecurity/Fake_news/app/urls.py
  CyberSecurity/Fake_news/app/views.py
  CyberSecurity/Fake_news/db.sqlite3
  CyberSecurity/Fake_news/manage.py
  DSA/C/Stack.c
  DSA/python/Stack.py
  DSA/python/Tree.py
Labels: hacktoberfest-accepted, hacktoberfest
